#!/usr/bin/env python3
"""Regenerate the committed CSV fixtures.

The fixtures are the reproducibility anchor: a study run against them can be re-run
byte-for-byte by anyone, with no network and no credentials. They are generated from the
synthetic provider with fixed seeds, so this script is idempotent — running it twice
produces identical files, and a diff means someone changed the generator.

Usage:
    python scripts/generate_fixtures.py [--out data/fixtures]
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "packages" / "tia" / "src"))

from tia.data.providers.csv_replay import write_fixture
from tia.data.providers.synthetic import build_synthetic_history

# Fixed anchor so the fixtures never depend on when the script ran.
ANCHOR = datetime(2026, 1, 6, 0, 0, tzinfo=UTC)

DATASETS: tuple[tuple[str, str, int, int], ...] = (
    # (symbol, timeframe, bars, seed)
    ("BTC-USD", "1m", 5_000, 101),
    ("ETH-USD", "1m", 5_000, 102),
    ("SPX-IDX", "1m", 5_000, 103),
    ("BTC-USD", "1h", 2_000, 111),
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="data/fixtures", type=Path)
    args = parser.parse_args()

    out: Path = args.out
    out.mkdir(parents=True, exist_ok=True)

    for symbol, timeframe, bars, seed in DATASETS:
        candles = build_synthetic_history(symbol, timeframe, bars, seed=seed, end=ANCHOR)
        path = out / f"{symbol}_{timeframe}.csv"
        write_fixture(path, candles)
        print(
            f"wrote {path} — {len(candles)} bars, "
            f"{candles[0].open_time.date()} .. {candles[-1].open_time.date()}, "
            f"close {candles[0].close:.2f} -> {candles[-1].close:.2f}"
        )

    readme = out / "README.md"
    readme.write_text(
        "# Fixtures\n\n"
        "Deterministic synthetic datasets generated by `scripts/generate_fixtures.py`.\n\n"
        "**These contain no real market data.** They exist so that experiments are\n"
        "reproducible without network access or credentials. A strategy that performs\n"
        "well on them has demonstrated that the pipeline works, and nothing about any\n"
        "real market.\n\n"
        "Regenerate with:\n\n"
        "```bash\npython scripts/generate_fixtures.py\n```\n\n"
        "The script is idempotent — a diff after running it means the generator changed.\n"
    )
    print(f"wrote {readme}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
