import { useCallback, useEffect, useState } from "react";
import { api, type NewsItem } from "../lib/api";
import type { Subscribe } from "../lib/stream";
import { useStreamEvent } from "../lib/stream";
import { Card, Empty, Pill, SimulationFootnote } from "../components/ui";
import { dateTime } from "../lib/format";

export function NewsView({ subscribe }: { subscribe: Subscribe }) {
  const [items, setItems] = useState<NewsItem[]>([]);
  const load = useCallback(() => { api.news(80).then(setItems).catch(() => undefined); }, []);
  useEffect(load, [load]);
  useStreamEvent(subscribe, "news.received", (data) =>
    setItems((previous) => [data as NewsItem, ...previous].slice(0, 80)),
  );

  return (
    <>
      <h1>News &amp; macro</h1>
      <div className="banner info">
        These headlines are <strong>generated by the scenario</strong>, not fetched from any
        news provider. They exist to exercise the path from a news item into the context
        layer. No real publisher is quoted and nothing here describes a real event.
      </div>

      <Card title={`Items (${items.length})`}>
        {items.length === 0 ? (
          <Empty message="No news in this scenario yet." />
        ) : (
          <div className="scroll tall">
            <table>
              <thead>
                <tr><th>Published</th><th>Headline</th><th>Symbols</th><th>Tone</th><th>Impact</th><th className="num">Relevance</th></tr>
              </thead>
              <tbody>
                {items.map((item) => (
                  <tr key={item.news_id}>
                    <td className="faint">{dateTime(item.published_at)}</td>
                    <td style={{ fontFamily: "var(--sans)" }}>{item.headline}</td>
                    <td className="faint">{item.symbols.join(", ")}</td>
                    <td>
                      <Pill
                        value={item.sentiment}
                        tone={item.sentiment === "bullish" ? "ok" : item.sentiment === "bearish" ? "bad" : ""}
                      />
                    </td>
                    <td><Pill value={item.impact} tone={item.impact === "high" ? "warn" : ""} /></td>
                    <td className="num">{item.relevance.toFixed(2)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
      <SimulationFootnote />
    </>
  );
}
